<?php
/**
 * Skeleton application to build voice applications for Amazon Alexa with phlexa, PHP and Mezzio
 *
 * @author     Ralf Eggert <ralf@travello.audio>
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @link       https://github.com/phoice/phlexa-mezzio-skeleton
 * @link       https://www.phoice.tech/
 * @link       https://www.travello.audio/
 */

$this->headTitle('Seite nicht gefunden');
?>
<br>
<div class="alert alert-danger">
  <h1>Seite nicht gefunden</h1>
  <h3>Es tut uns leid!</h3>
  <p>
    Leider konnte die aufgerufene Seite nicht gefunden werden! Der Techniker
    ist informiert!
  </p>
</div>
<hr>
<p class="text-center">
  <a class="btn btn-success" href="https://www.travello.audio/#contact">
    Impressum
  </a>
</p>
