<?php
/**
 * Skeleton application to build voice applications for Amazon Alexa with phlexa, PHP and Zend\Expressive
 *
 * @author     Ralf Eggert <ralf@travello.audio>
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @link       https://github.com/phoice/phlexa-expressive-skeleton
 * @link       https://www.phoice.tech/
 * @link       https://www.travello.audio/
 */

$this->headTitle('Fehler');
?>
<br>
<div class="alert alert-danger">
  <h1>Es ist ein Fehler aufgetreten</h1>
  <h3>Es tut uns leid!</h3>
  <p>Leider ist ein Fehler aufgetreten! Der Techniker ist informiert!</p>
</div>
<hr>
<p class="text-center">
  <a class="btn btn-success" href="https://www.travello.audio/#contact">
    Impressum
  </a>
</p>
